development:
  adapter: mysql
  database: depot_development
  host: localhost
  username: root
  password: Trabajo

test:
  adapter: mysql
  database: depot_test
  host: localhost
  username: 
  password:

production:
  adapter: mysql
  database: depot_development
  host: localhost
  username: 
  password: 
