development:
  adapter: mysql
  database: depot_development
  host: localhost
  username: root
  password: password

test:
  adapter: mysql
  database: depot_test
  host: localhost
  username: root    
  password: password

production:
  adapter: mysql
  database: depot_development
  host: localhost
  username: root
  password: password
